### ISSUE TITLE
SDK Timegraph API PoC -3

### ISSUE THREAD

**Issue by isabellelaususan** [Analog-Labs/timechain#104]
PoC -3 
- [x] Authentication of users (Conceptualize detailed flow) [Ref](https://drive.google.com/file/d/10dgNt2IUQXfsifMHQ11CWKXUurgvcQ_X/view?ts=63f5acbe)
- [x] Integration with wallet (as a support to use wallet as identity)
- [x] Deployment of PoC -3

**Tasks for Sprint: 31 Mar - 13 Apr**
- [x] - Task Management interfaces for Timegraph CLI & API (Ali Tanveer)

**Tasks for Sprint: 14 Apr - 27 Apr**
- [x] Views mutation
- [x] Documentation 
   - [x] Design docs (FIGMA updates) 
   - [x] Usage docs GH
- [x] Test cases
Implement requirements:
- [x] Dependencies for Marketplace integration (Collab with Keith & Product)
- [x] Design & Implementation of Data structures (Collab with Zain and Junius)
