### ISSUE TITLE
GMPv2 Tracking Issues

### ISSUE THREAD

**Issue by Lohann** [Analog-Labs/timechain#1208]
- [x] https://github.com/Analog-Labs/timechain/issues/1206
- [ ] [blocked] https://github.com/Analog-Labs/timechain/issues/1207
- [ ] https://github.com/Analog-Labs/timechain/issues/1204
- [ ] Decide about the execution ordering mechanism.
