### ISSUE TITLE
Implement task execution tokenomics

### ISSUE THREAD

**Issue by isabellelaususan** [Analog-Labs/timechain#640]
**Task:**
Implement task execution tokenomics

**Success Criteria:** complete all issues and merge all PRs linked under task checklist

**Task Checklist** 
- [x] Read task tokenomics.  #632 #633 
- [x] Reassign read task upon timeout. #646 #633
- [x] Write task tokenomics. #651 #665

**References**
- [GMP PRD](https://www.notion.so/teamanalog/GMP-Product-Requirement-b2e010919fd448c1aa3419d5dffdadfd?pvs=4)
- [GMP Phase 2 - Requirements](https://www.notion.so/teamanalog/WIP-GMP-Requirements-Post-Phase-1-fb5c0158065847f88ff4d4db30e53f65?pvs=4)
- [GMP Phase 1 - Diagrams](https://www.figma.com/file/12WeZKS0UeKOVYFz70nKvd/GMP-Phase-1-(Transaction-Execution-Flow-and-Fees)?type=whiteboard&node-id=0-1&t=ySJogV7epprSQOBn-0)
